version: "3.7"

services: 
  estacione_aqui:
    image: postgres
    container_name: estacione_aqui
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes: 
      - pgdata:/data/postgres

  app: 
    build: .
    container_name: estacione_aqui_back
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links:
      - estacione_aqui
    depends_on: 
      - estacione_aqui
volumes:
  pgdata: 
    driver: local