version: "3.7"

services: 
  4Medicine_database:
    image: postgres
    container_name: estacione_aqui
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes: 
      - pgdata:/data/postgres
volumes:
  pgdata: 
    driver: local